/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-07-28 12:37:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.User;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.User");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>User Home Page</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\"  href=\"style/design.css\"/>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery17.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            $(document).ready(function(){\n");
      out.write("                \n");
      out.write("                $(\".cont-menu ul li\").click(function(){\n");
      out.write("                    var cl=$(this).html().toLowerCase().replace(/\\s+/g,'-');\n");
      out.write("                    $('.cont .sub-cont').hide(0,function(){$('.cont .'+cl).show();});\n");
      out.write("                    $('.cont .'+cl).show();\n");
      out.write("                    \n");
      out.write("                });\n");
      out.write("                $('.btn-update').click(function (){\n");
      out.write("                    $('.addrss-update').submit();\n");
      out.write("                });\n");
      out.write("                $('.btn-update-password').click(function (){\n");
      out.write("                    $('.update-password').submit();\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
 if(request.getSession().getAttribute("userid")==null){
            response.sendRedirect("login.jsp");
        }else{ 
      out.write("\n");
      out.write("        <div class=\"pageheading\">Welcome Mr. ");
      out.print(request.getSession(true).getAttribute("username").toString() );
      out.write("<a href=\"logout\">Logout</a></div>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("        <div class=\"cont-wrapper\">\n");
      out.write("            <div class=\"cont-menu\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>Change Address</li>\n");
      out.write("                    <li>Change Password</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"cont\">\n");
      out.write("                <div class=\"change-address sub-cont\">\n");
      out.write("                    ");

                        User user=(User)request.getAttribute("curuser");
                       
                    
      out.write("\n");
      out.write("                    <form class=\"addrss-update\" method=\"post\" action=\"updateaddress\">\n");
      out.write("                        <input type=\"hidden\" name=\"address\" value=\"");
      out.print(user.addValid);
      out.write("\"/>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>First Name</label><input type=\"text\" name=\"fname\" value=\"");
      out.print(user.getFName());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Last Name</label><input type=\"text\" name=\"lname\" value=\"");
      out.print(user.getLName());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Email Id</label><input type=\"text\" name=\"email\" readonly value=\"");
      out.print(user.getEmail());
      out.write("\"/>\n");
      out.write("                        </div> \n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Address Line 1</label>\n");
      out.write("                            <input type=\"text\" name=\"addresslineone\" value=\"");
      out.print(user.getLine1());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Address Line 2</label>\n");
      out.write("                            <input type=\"text\" name=\"addresslinetwo\" value=\"");
      out.print(user.getLine2());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>City</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"city\" value=\"");
      out.print(user.getCity());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>State</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"state\" value=\"");
      out.print(user.getState());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Country</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"country\" value=\"");
      out.print(user.getCountry() );
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Zip code</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"zipcode\" value=\"");
      out.print(user.getZip() );
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"btn btn-cancel\">Cancel</div>\n");
      out.write("                        <div class=\"btn btn-update\">Update</div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"change-password sub-cont\">\n");
      out.write("                    <form class=\"update-password\" method=\"post\" action=\"updatepassword\">\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Old Password</label>\n");
      out.write("                            <input type=\"password\" name=\"oldpassword\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>New Password</label>\n");
      out.write("                            <input type=\"password\" name=\"newpassword\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Conform Password</label>\n");
      out.write("                            <input type=\"password\" name=\"confrmpassword\"/>\n");
      out.write("                        </div>   \n");
      out.write("                        <div class=\"btn btn-cancel-pass\">Cancel</div>\n");
      out.write("                        <div class=\"btn btn-update-password\">Update</div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
