/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-07-31 10:25:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.Utils;
import org.json.JSONObject;
import java.util.*;
import utils.DbUtils;
import org.json.JSONArray;
import utils.User;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.DbUtils");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("utils.User");
    _jspx_imports_classes.add("utils.Utils");
    _jspx_imports_classes.add("org.json.JSONArray");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>User Home Page</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\"  href=\"style/design.css\"/>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery17.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            $(document).ready(function() {\n");
      out.write("\n");
      out.write("                $.ajax({\n");
      out.write("                    url: '/search',\n");
      out.write("                    type: 'POST',\n");
      out.write("                    data: {searchword: ''},\n");
      out.write("                    success: function(data) {\n");
      out.write("                        $('.search-result').html(data.toString());\n");
      out.write("                    },\n");
      out.write("                    error: function(e) {\n");
      out.write("                        $('.search-result').html(e.responseText);\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                $('.searchbox').blur(function() {\n");
      out.write("\n");
      out.write("                    $.ajax({\n");
      out.write("                        url: '/search',\n");
      out.write("                        type: 'POST',\n");
      out.write("                        data: {searchword: $(this).val()},\n");
      out.write("                        success: function(data) {\n");
      out.write("                            $('.search-result').html(data.toString());\n");
      out.write("                        },\n");
      out.write("                        error: function(e) {\n");
      out.write("                            $('.search-result').html(e.responseText);\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                $('.contact-heading').click(function() {\n");
      out.write("                    $(this).parent('.contact').parent('.contacts').children('.contact').children('.contact-details').hide(300);\n");
      out.write("                    $(this).parent('.contact').children('.contact-details').toggle(300);\n");
      out.write("                });\n");
      out.write("                $(\".cont-menu ul li\").click(function() {\n");
      out.write("                    var cl = $(this).html().toLowerCase().replace(/\\s+/g, '-');\n");
      out.write("                    $('.cont .sub-cont').hide(0, function() {\n");
      out.write("                        $('.cont .' + cl).show();\n");
      out.write("                    });\n");
      out.write("                    // $('.cont .' + cl).show();\n");
      out.write("\n");
      out.write("\n");
      out.write("                });\n");
      out.write("                $('.btn-update').click(function() {\n");
      out.write("                    $('.addrss-update').submit();\n");
      out.write("                });\n");
      out.write("                $('.btn-update-password').click(function() {\n");
      out.write("\n");
      out.write("                    if ($('.newpassword').val() !== $('.confrmpassword').val()) {\n");
      out.write("                        alert(\"Password is mismatch\");\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    if ($('.newpassword').val() === \"\" || $('.oldpassword').val() === \"\") {\n");
      out.write("                        alert(\"one or more field(s) are empty\");\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("                    $('.update-password').submit();\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            .contact-heading .btn{\n");
      out.write("                float: right;\n");
      out.write("                margin-top: -2px;\n");
      out.write("                height: 17px;\n");
      out.write("                font-size: 16px;\n");
      out.write("                padding: 2px 10px 2px 10px;\n");
      out.write("            }\n");
      out.write("            /*    .btn-delete{\n");
      out.write("                    position: relative;\n");
      out.write("                    top: -37px;\n");
      out.write("                    left: 88px;\n");
      out.write("                }*/\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
 User user = (User) request.getAttribute("curuser");

        
      out.write("\n");
      out.write("\n");
      out.write("        ");
 if (request.getSession().getAttribute("userid") == null) {
                response.sendRedirect("login");
                return;
            } else {
                if (user == null) {
                    user = User.getUser(request.getSession().getAttribute("userid").toString());
                }
        
      out.write("\n");
      out.write("        <div class=\"pageheading\">Welcome ");
      out.print(request.getSession(true).getAttribute("username").toString());
      out.write("<a class=\"logout\" href=\"logout\">Logout</a></div>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"cont-wrapper\">\n");
      out.write("            <div class=\"cont-menu\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>User Details</li>\n");
      out.write("                    <li>Change Address</li>\n");
      out.write("                    <li>Change Password</li>\n");
      out.write("                    <li>Contacts</li>\n");
      out.write("                    <li>Add Contact</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"cont\">\n");
      out.write("                <div class=\"user-details sub-cont\">\n");
      out.write("                    <div class=\"user\">\n");
      out.write("                        <ul>\n");
      out.write("                            <li><span>First Name:</span> ");
      out.print(user.getFName());
      out.write("</li>\n");
      out.write("                            <li><span>Last Name :</span> ");
      out.print(user.getLName());
      out.write("</li>\n");
      out.write("                            <li><span>Email :</span>");
      out.print(user.getEmail());
      out.write("</li>\n");
      out.write("                            <li><span>Address Line1: </span>");
      out.print(user.getLine1());
      out.write("</li>\n");
      out.write("                            <li><span>Address Line2: </span>");
      out.print(user.getLine2());
      out.write("</li>\n");
      out.write("                            <li><span>City :</span>");
      out.print(user.getCity());
      out.write("</li>\n");
      out.write("                            <li><span>State :</span>");
      out.print(user.getState());
      out.write("</li>\n");
      out.write("                            <li><span>Country :</span>");
      out.print(user.getCountry());
      out.write("</li>\n");
      out.write("                            <li><span>Zip code :</span>");
      out.print(user.getZip());
      out.write("</li>\n");
      out.write("\n");
      out.write("                        </ul>  \n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"change-address sub-cont\">\n");
      out.write("                    <form class=\"addrss-update\" method=\"post\" action=\"updateaddress\">\n");
      out.write("                        <input type=\"hidden\" name=\"address\" value=\"");
      out.print(user.addValid);
      out.write("\"/>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>First Name</label><input type=\"text\" name=\"fname\" value=\"");
      out.print(user.getFName());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Last Name</label><input type=\"text\" name=\"lname\" value=\"");
      out.print(user.getLName());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Email Id</label><input type=\"text\" name=\"email\" readonly value=\"");
      out.print(user.getEmail());
      out.write("\"/>\n");
      out.write("                        </div> \n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Address Line 1</label>\n");
      out.write("                            <input type=\"text\" name=\"addresslineone\" value=\"");
      out.print(user.getLine1());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Address Line 2</label>\n");
      out.write("                            <input type=\"text\" name=\"addresslinetwo\" value=\"");
      out.print(user.getLine2());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>City</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"city\" value=\"");
      out.print(user.getCity());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>State</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"state\" value=\"");
      out.print(user.getState());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Country</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"country\" value=\"");
      out.print(user.getCountry());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Zip code</label><br/>\n");
      out.write("                            <input type=\"text\" name=\"zipcode\" value=\"");
      out.print(user.getZip());
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"btn btn-cancel\">Cancel</div>\n");
      out.write("                        <div class=\"btn btn-update\">Update</div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"change-password sub-cont\">\n");
      out.write("                    <form class=\"update-password\" method=\"post\" action=\"updatepassword\">\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Old Password</label>\n");
      out.write("                            <input class=\"oldpassword\" type=\"password\" name=\"oldpassword\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>New Password</label>\n");
      out.write("                            <input class=\"newpassword\" type=\"password\" name=\"newpassword\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Conform Password</label>\n");
      out.write("                            <input class=\"confrmpassword\" type=\"password\" name=\"confrmpassword\"/>\n");
      out.write("                        </div>   \n");
      out.write("                        <div class=\"btn btn-cancel-pass\">Cancel</div>\n");
      out.write("                        <div class=\"btn btn-update-password\">Update</div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"contacts sub-cont\">\n");
      out.write("                    <div contact-heading>Search: <input type=\"text\" class=\"searchbox\"></div>\n");
      out.write("\n");
      out.write("                    <div class=\"search-result\">\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <!-- <div class=\"contact\">\n");
      out.write("                         <div class=\"contact-heading\">Karthikeyan\n");
      out.write("                             <div class=\"btn\">Edit</div><div class=\"btn btn-delete\">Delete</div>\n");
      out.write("                         </div>\n");
      out.write("                         <div class=\"contact-details\">\n");
      out.write("                             <div class=\"lbl\">Name : Karthikeyan</div>\n");
      out.write("                             <div class=\"lbl\">Email : Karthikeyan@chargebee.com</div>\n");
      out.write("                             <div class=\"lbl\">Phone : 9994901398</div>\n");
      out.write("                             <div class=\"lbl\">Home : 144564576434</div>\n");
      out.write("                             <div class=\"lbl\">Home : 144564576434</div>\n");
      out.write("                             <div class=\"lbl\">Home : 144564576434</div>\n");
      out.write(" \n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"contact\">\n");
      out.write("                         <div class=\"contact-heading\">Karthikeyan</div>\n");
      out.write("                         <div class=\"contact-details\">  \n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"contact\">\n");
      out.write("                         <div class=\"contact-heading\">Karthikeyan</div>\n");
      out.write("                         <div class=\"contact-details\">\n");
      out.write(" \n");
      out.write("                         </div>\n");
      out.write("                     </div>-->\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                <div class=\"add-contact sub-cont\">\n");
      out.write("                    <form method=\"post\" action=\"addcontact\">\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Name :</label> <input type=\"text\" name=\"contactname\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>Email :</label><input type=\"email\" name=\"contactemail\"/>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        ");

                            for (Utils.MobileTypes type : Utils.MobileTypes.values()) {
                        
      out.write("\n");
      out.write("                        <div class=\"input-grp\">\n");
      out.write("                            <label>");
      out.print(type.name().toLowerCase());
      out.write(" : </label><input type=\"text\" name=\"");
      out.print(type.name());
      out.write("\"/>\n");
      out.write("                        </div> \n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("                        <input type=\"reset\" value=\"Clear\"/>\n");
      out.write("                        <input style=\"margin-left: 10px;\" type=\"submit\" value=\"Add\"/>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
